# Generated by Django 4.0.3 on 2022-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
