# Generated by Django 4.0.3 on 2022-03-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0005_alter_payment_options_alter_payment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.type'),
        ),
    ]
