# Generated by Django 4.0.3 on 2022-03-23 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('payments', '0006_ticket_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='event_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.type', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ticket',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.type', verbose_name='Type'),
        ),
    ]
