# Generated by Django 4.0.3 on 2022-03-23 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0007_payment_event_type_alter_payment_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.type', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='initial_usages',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Initial usages'),
        ),
    ]
