# Generated by Django 4.0.3 on 2022-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer',
            field=models.BooleanField(default=False, verbose_name='Trener'),
        ),
    ]
