# Generated by Django 4.0.3 on 2022-03-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trainer',
            field=models.BooleanField(default=False, verbose_name='trainer'),
        ),
    ]
