# Generated by Django 4.0.3 on 2022-03-26 10:08

import dateutil.utils
from django.db import migrations, models

import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_register_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschema',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=events.models.tomorrow, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eventschema',
            name='date_from',
            field=models.DateField(default=dateutil.utils.today, verbose_name='Date from'),
        ),
        migrations.AlterField(
            model_name='eventschema',
            name='date_to',
            field=models.DateField(default=events.models.tomorrow, verbose_name='Date to'),
        ),
    ]
