# Generated by Django 4.0.3 on 2022-04-09 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_eventschema_subtitle_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eventschema',
            options={'ordering': ['-id'], 'verbose_name': 'Event schema', 'verbose_name_plural': 'Events schemas'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-id'], 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_as_participant', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='ticket_usages_left_after_register',
            field=models.SmallIntegerField(verbose_name="Ticket's usages left after registering"),
        ),
    ]
